apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
   name: nginx-pa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: replicawala
  minReplicas: 3
  maxReplicas: 7
  metrics:
    - type: Resource
      resource:
       name: cpu
       target:
          type: Utilization
          averageUtilization: 50
