apiVersion: v1
kind: PersistentVolume
metadata:
    name: awspv
    labels:
      app: dev
spec:
  capacity:
     storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: {give nfs dns}
    path: /test

