apiVersion: v1
kind: PersistentVolume
metadata:
    name: awspv
    labels:
      app: dev
spec:
  capacity:
     storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: fs-0033971b7835763f8.efs.ap-south-1.amazonaws.com
    path: /test

